config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :users, except: [:edit, :update, :destroy] do
    resources :activities, only: [ :new, :create, :index ]
    resources :groups, only: [ :new, :create, :index, :show ]
  end

  devise_scope :user do
    root 'users/sessions#new'
  end

  get "/profile", to: 'users#show'
  # get "*path", to: redirect('/')
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { in: 3..100 }
  validates :icon, presence: true
  validates_uniqueness_of :name, scope: :author_id

  belongs_to :author, class_name: 'User'
  has_one_attached :icon
  has_many :activities

  def activities_duration_total
    amount_array = activities.map { |activity| activity.amount.to_i }
    amount_array.sum
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      redirect_to user_groups_path, notice: 'New group created successfully!'
    else
      render 'new'
    end
  end

  def index
    @group = Group.new
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
    group_activities
    @activities_duration_total = @group.activities_duration_total
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def group_activities
    @group_activities = @group.activities.latest_first
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_img_url(group)
    url_for(group.icon) if group.icon.attached?
  end

  def create_group_button(current_user)
    content_tag :nav, class: 'navbar is-fixed-bottom' do
      content_tag :div, class: 'columns is-centered' do
        content_tag :div, class: 'column' do
          content_tag :div, class: 'box has-text-centered has-background-success' do
            link_to 'Create a New Group', new_user_group_path(current_user),
                    class: 'button is-fullwidth is-success is-inverted is-outlined'
          end
        end
      end
    end
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group, url: user_groups_path) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :name,
                  label: 'Group Name',
                  required: true,
                  autofocus: true,
                  placeholder: 'Enter a group name',
                  input_html: { autocomplete: "name", class: "input" },
                  wrapper: false,
                  label_html: { class: "label"} %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :icon,
                  as: :file,
                  label: "Upload Icon",
                  required: true,
                  input_html: { class: "input" },
                  wrapper: false,
                  label_html: { class: "label"} %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.button :submit, "Create Group", class: "button is-primary" %>
    </div>
  </div>
<% end %>
<br>

app/views/groups/_group.html.erb
<div class="group-tile has-text-centered">
  <div class="">
    <img class="group-tile-img is-centered" src="<%= group_img_url(group) %>" alt="group-image">
  </div>
  <div class="">
    <p class="title is-5 has-text-centered"><%= link_to group.name, user_group_path(current_user, group), class: 'custom-link' %></p>
  </div>
</div>

app/views/groups/index.html.erb
<div class="columns is-centered">
  <div class="column is-centered">
    <div class="group-tile-wrapper">
      <%= render @groups %>
    </div>
  </div>
</div>
<%= create_group_button(current_user) %>

app/views/groups/new.html.erb
<div class="columns is-centered mb-6">
  <div class="column is-two-thirds-tablet is-half-desktop has-background-white-bis">
    <h2 class="title is-2 has-text-centered">Create a New Group</h2>
    <%= render 'groups/form' %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="has-background-white-ter">
  <div class="has-text-centered mb-6">
    <h2 class="title is-3 pt-3"><%= "All #{@group.name} Activities" %></h2>
  </div>
  <%= render 'activities/total_hours' %>
  <%= render @group_activities %>
  <br>
  <br>
  <br>
  <%= create_activity_button(current_user) %>
</div>